### PR TITLE
Remove package-lock.json

### PR DESCRIPTION
**Pull request by haeungun**
`package-lock.json` is automatically generated for any operations where npm modifies either the `node_modules` tree, or `package.json`.
So it would be nice to remove this file from github.

ISSUE=none

### CODE REVIEW

**Comment by byeolbit** [comment]
How about add this file to .gitignore?

**Comment by haeungun** [comment]
Sure ! I already did it, too. :)

**Comment by byeolbit** [comment]
Ah, I missed it. LGTM :)

**Comment by byeolbit** [comment]
merged

**Pull request merged**
